<a href="https://colab.research.google.com/github/HagarIbrahiem/ML-Classification_Models/blob/main/Multi_label_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml ('mnist_784', version=1)

In [2]:
X, y = mnist['data'],mnist['target']
import numpy as np
y.shape

(70000,)

In [5]:
y = y.astype(np.uint8)
y.shape

(70000,)

In [9]:
X_train , X_test, y_train, y_test = X[:60000],X[60000:], y[:60000],y[60000:]

In [11]:
y_train_large = (y_train >=7)
y_train_odd = (y_train %2 ==1)
y_multilabel = np.c_[y_train_large , y_train_odd] #Concatenate
y_multilabel

array([[False,  True],
       [False, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [ True, False]])

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train , y_multilabel)

KNeighborsClassifier()

In [14]:
digit = X.to_numpy()[2]

In [15]:
X_test_knn_clf.predict([digit])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([[False, False]])

In [23]:
y_test_large = (y_test >= 7)
y_tets_odd = (y_test % 2 ==1)
y_test_multilabel = np.c_[y_test_large ,y_tets_odd ]

X_tets_pred = knn_clf.predict(X_test)


In [35]:
X_tets_pred[0]

array([ True,  True])

In [37]:
y_test.head(1)

60000    7
Name: class, dtype: uint8

In [41]:
from sklearn.metrics import f1_score
from sklearn.model_selection  import cross_val_predict 

y_train_knn_pred = cross_val_predict(knn_clf, X_train, y_multilabel, cv=3)
f1_score(y_multilabel, y_train_knn_pred, average="macro")

0.976410265560605